name: 'vasama/actions: setup-conan-index'
description: 'Download, extract and set up vasama/conan-index'
author: 'Lauri Vasama'

runs:
  using: composite
  steps:
  - name: Download conan-index archive
    shell: pwsh
    run: Invoke-WebRequest -Uri 'https://github.com/vasama/conan-index/archive/refs/heads/main.zip' -OutFile "$ENV:RUNNER_TEMP/vsm-conan-index.zip"

  - name: Extract conan-index files
    shell: pwsh
    run: Expand-Archive -LiteralPath "$ENV:RUNNER_TEMP/vsm-conan-index.zip" -DestinationPath "$ENV:RUNNER_TEMP/vsm-conan-index"

  - name: Set up local Conan remote
    shell: pwsh
    run: conan remote add vasama "$ENV:RUNNER_TEMP/vsm-conan-index/conan-index-main"
