compiler:
  gcc:
    sanitize_address: [null, true]
    sanitize_thread: [null, true]
    sanitize_undefined: [null, true]
  clang:
    sanitize_address: [null, true]
    sanitize_thread: [null, true]
    sanitize_undefined: [null, true]
  msvc:
    sanitize_address: [null, true]
