name: 'vasama/actions: setup'
description: 'Download and extract action script library'
author: 'Lauri Vasama'

runs:
  using: composite
  steps:
    - name: Download library archive
      shell: pwsh
      run: Invoke-WebRequest -Uri 'https://github.com/vasama/actions/archive/refs/heads/main.zip' -OutFile /tmp/vsm-actions.zip

    - name: Extract library files
      shell: pwsh
      run: Expand-Archive -LiteralPath /tmp/vsm-actions.zip -DestinationPath /tmp/vsm-actions-tmp

    - name: Copy library files (temporary for testing)
      shell: pwsh
      run: |
        Copy-Item -Recurse -LiteralPath /tmp/vsm-actions-tmp/actions-main/library -Destination /tmp/vsm-actions
        chmod +x /tmp/vsm-actions/scripts/*.ps1
        chmod +x /tmp/vsm-actions/scripts/Utilities/*.ps1
        chmod +x /tmp/vsm-actions/scripts/CxxAnalysisModules/*.ps1
