on:
  workflow_call: {}

jobs:
  merge-linux:
    name: linux

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vasama/actions-ubuntu:v0

    steps:
    - uses: actions/checkout@v4
    - uses: vasama/actions/setup@main

    - name: Check branch
      run: |
        /tmp/vsm-actions/scripts/Test-CxxProjectBranch.ps1 -BaseRef "${{ inputs.base_ref }}"